- hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
  - name: copy index file
    copy:
      src: index.html
      dest: /var/www/html/index.html
      remote_src: yes
    notify:
    - start httpd service
  - name: debug info
    debug:
      msg: "after copy task done"
  handlers:
  - name: start httpd service
    service:
      name: httpd
      state: started
