- hosts: all
  become: true
  vars:
   package_name: httpd
  tasks:
  - name: install-httpd
    yum:
     name: "{{package_name}}"
     state: latest
  - name: copy index.html file
    copy:
     src: index.html
     dest: /var/www/html/index.html
  - name: start httpd service
    service:
     name: "{{package_name}}"
     state: started
