#define variable within playbook
- hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: install httpd
    yum:
      name: "{{package_name}}"
      state: present
  - name: copy index file
    template:
      src: index.html
      dest: /var/www/html/index.html
    notify:
    - start "{{package_name}}" service
  - name: debug info
    debug:
      msg: "after copy task done"
  handlers:
  - name: start "{{package_name}}" service
    service:
      name: httpd
      state: started

# ansible-playbook installHttpd.yml  --extra-vars package_name=httpd --extra-vars name=balaji
